server:
  port: 8761

eureka:
  instance:
    hostname: eureka-server
    prefer-ip-address: false

  client:
    registerWithEureka: false      # Este servidor no se registra en otro
    fetchRegistry: false           # No obtiene registros de otros
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

  server:
    # 💡 Desactiva la autoconservación que provoca el banner rojo
    enable-self-preservation: true

    # 💡 Baja el umbral para que no aparezca la advertencia aun si lo reactivas
    renewal-percent-threshold: 0.10
    renewal-threshold-update-interval-ms: 10000

    # 💡 Control de limpieza de instancias caducadas
    eviction-interval-timer-in-ms: 60000
    waitTimeInMsWhenSyncEmpty: 0
    response-cache-update-interval-ms: 5000

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.netflix.eureka: INFO
    org.springframework.cloud.netflix.eureka: INFO
